In [1]:
from keras.preprocessing import image
import numpy as np
import os
import tensorflow as tf
import h5py

datamodel = h5py.File("E:\\fbiz\\api\chicken.h5", "r")
model = tf.keras.models.load_model(datamodel)

Using TensorFlow backend.


In [2]:
from keras.applications.resnet50 import preprocess_input
def load_image(img_path, size,show=False):

    img = image.load_img(img_path, target_size=(size, size))
    img_tensor = image.img_to_array(img)
    # (1, height, width, channels), add a dimension because the model expects this shape: (batch_size, height, width, channels)
    img_tensor = np.expand_dims(img_tensor, axis=0)
    # imshow expects values in the range [0, 1]
    img_tensor /= 255.

    return img_tensor

In [3]:
path = "test/marek/"

for img in os.listdir(path):
    new_img = load_image(os.path.join(path, img), 64)
    # check prediction
    pred = model.predict(new_img)
    print(pred)
    rs = max(pred[0])
    if rs < 90:
        isCorrect = False
    pred = pred[0]
    pred = pred.tolist()
    idx = pred.index(rs)
    
    print(idx)

[[5.0620771e-13 6.1092584e-07 9.9999928e-01 1.2271417e-07 5.7546703e-13]]
2
[[1.5001126e-06 9.4275284e-19 1.4325809e-06 9.9999130e-01 5.7574775e-06]]
3
[[3.9160891e-14 1.3281929e-18 9.9999976e-01 5.1195083e-11 2.6403941e-07]]
2
[[2.5270394e-05 3.6531247e-08 3.7351722e-08 8.2994802e-08 9.9997461e-01]]
4
[[1.1307906e-07 2.7420674e-08 9.8968518e-04 1.4363966e-09 9.9901021e-01]]
4
[[6.3299121e-05 8.0517000e-14 5.0698929e-03 1.6242690e-02 9.7862405e-01]]
4
[[6.5667919e-05 8.7455856e-09 4.3236527e-05 4.4050245e-07 9.9989069e-01]]
4
[[1.9253150e-06 1.0883166e-06 9.6315803e-04 6.0189137e-08 9.9903381e-01]]
4
[[2.2154043e-09 4.1624986e-08 1.0933229e-06 2.3506330e-13 9.9999881e-01]]
4
[[3.9126212e-07 5.2605975e-10 1.5708354e-06 6.2713095e-15 9.9999809e-01]]
4
[[4.6370100e-05 1.0914708e-05 9.9568105e-01 4.2613694e-03 2.2152558e-07]]
2
[[1.9710875e-07 4.8955627e-08 1.2369869e-01 5.5737871e-08 8.7630105e-01]]
4
[[1.6382169e-08 1.7413325e-09 4.5290295e-02 9.5469290e-01 1.6683794e-05]]
3
[[5.4520402e